/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';
import '@stencil/state-tunnel';

import {
  MatchResults,
} from '@stencil/router';
import {
  Model200,
} from './services/model/weather/models';

declare global {

  namespace StencilComponents {
    interface AppHome {
      'defaultQ': string;
    }
  }

  interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {
      'defaultQ'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppProfile {
      'match': MatchResults;
    }
  }

  interface HTMLAppProfileElement extends StencilComponents.AppProfile, HTMLStencilElement {}

  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };
  interface HTMLElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  interface ElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-profile': JSXElements.AppProfileAttributes;
    }
  }
  namespace JSXElements {
    export interface AppProfileAttributes extends HTMLAttributes {
      'match'?: MatchResults;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppRoot {

    }
  }

  interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-root': JSXElements.AppRootAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRootAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppWeatherQuery {
      'defaultQ': string;
    }
  }

  interface HTMLAppWeatherQueryElement extends StencilComponents.AppWeatherQuery, HTMLStencilElement {}

  var HTMLAppWeatherQueryElement: {
    prototype: HTMLAppWeatherQueryElement;
    new (): HTMLAppWeatherQueryElement;
  };
  interface HTMLElementTagNameMap {
    'app-weather-query': HTMLAppWeatherQueryElement;
  }
  interface ElementTagNameMap {
    'app-weather-query': HTMLAppWeatherQueryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-weather-query': JSXElements.AppWeatherQueryAttributes;
    }
  }
  namespace JSXElements {
    export interface AppWeatherQueryAttributes extends HTMLAttributes {
      'defaultQ'?: string;
      'onQChanged'?: (event: CustomEvent) => void;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppWeatherResult {
      'weather': Model200;
    }
  }

  interface HTMLAppWeatherResultElement extends StencilComponents.AppWeatherResult, HTMLStencilElement {}

  var HTMLAppWeatherResultElement: {
    prototype: HTMLAppWeatherResultElement;
    new (): HTMLAppWeatherResultElement;
  };
  interface HTMLElementTagNameMap {
    'app-weather-result': HTMLAppWeatherResultElement;
  }
  interface ElementTagNameMap {
    'app-weather-result': HTMLAppWeatherResultElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-weather-result': JSXElements.AppWeatherResultAttributes;
    }
  }
  namespace JSXElements {
    export interface AppWeatherResultAttributes extends HTMLAttributes {
      'weather'?: Model200;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
